version: '3'
services:
  app:
    container_name: heri_app
    build: ./docker/php
    volumes:
      - ./src/:/var/www/src
  next:
    container_name: heri_next
    build: ./docker/next
    tty: true
    ports:
        - ${NEXT_PORT}:3000
    volumes:
      - ./next:/var/www/next
    networks:
      - default
  nginx:
    container_name: heri_nginx
    image: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./src:/var/www/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/src
    depends_on:
      - app
  database:
    container_name: heri_database
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
