version: '3'
services:
  app:
    container_name: heri_app
    build: ./docker/php
    ports:
      - 5173:5173
    volumes:
      - ./src/:/var/www/src
  nginx:
    container_name: heri_nginx
    image: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./src:/var/www/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/src
    depends_on:
      - app
  database:
    container_name: heri_database
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
  mailhog:
    container_name: heri_mailhog
    image: mailhog/mailhog:latest
    platform: linux/amd64
    ports:
      - "8025:8025"
      - "1025:1025"
