version: '3'
services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./src/:/var/www/src
  next:
    container_name: next
    build: ./docker/next
    tty: true
    ports:
        - ${NEXT_PORT}:3000
    volumes:
      - ./next:/var/www/next
    networks:
      - default
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./src:/var/www/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/src
    depends_on:
      - app
  db:
    container_name: db
    image: mysql:8.0
    ports:
      - ${DB_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
