import type { Metadata } from 'next'
import '../style/style.scss'
import Header from '@/components/layout/user/Header'

export const metadata: Metadata = {
    title: 'HERI',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="jp">
            <body className='user'>
                <Header />
                {children}
            </body>
        </html>
    )
}
